
package com.mac.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerDetails", targetNamespace = "http://www.mac.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerDetails {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.mac.client.Customer
     * @throws InvalidInputException_Exception
     */
    @WebMethod
    @WebResult(name = "Customer", targetNamespace = "")
    @RequestWrapper(localName = "customerDetails", targetNamespace = "http://www.mac.com", className = "com.mac.client.CustomerDetails_Type")
    @ResponseWrapper(localName = "customerDetailsResponse", targetNamespace = "http://www.mac.com", className = "com.mac.client.CustomerDetailsResponse")
    @Action(input = "http://www.mac.com/CustomerDetails/customerDetailsRequest", output = "http://www.mac.com/CustomerDetails/customerDetailsResponse", fault = {
        @FaultAction(className = InvalidInputException_Exception.class, value = "http://www.mac.com/CustomerDetails/customerDetails/Fault/InvalidInputException")
    })
    public Customer customerDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws InvalidInputException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.mac.client.Qualification
     * @throws InvalidInputException_Exception
     */
    @WebMethod
    @WebResult(name = "Qualification", targetNamespace = "")
    @RequestWrapper(localName = "customerQualifications", targetNamespace = "http://www.mac.com", className = "com.mac.client.CustomerQualifications")
    @ResponseWrapper(localName = "customerQualificationsResponse", targetNamespace = "http://www.mac.com", className = "com.mac.client.CustomerQualificationsResponse")
    @Action(input = "http://www.mac.com/CustomerDetails/customerQualificationsRequest", output = "http://www.mac.com/CustomerDetails/customerQualificationsResponse", fault = {
        @FaultAction(className = InvalidInputException_Exception.class, value = "http://www.mac.com/CustomerDetails/customerQualifications/Fault/InvalidInputException")
    })
    public Qualification customerQualifications(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws InvalidInputException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.mac.client.Customer>
     */
    @WebMethod
    @WebResult(name = "Customer", targetNamespace = "")
    @RequestWrapper(localName = "allCustomers", targetNamespace = "http://www.mac.com", className = "com.mac.client.AllCustomers")
    @ResponseWrapper(localName = "allCustomersResponse", targetNamespace = "http://www.mac.com", className = "com.mac.client.AllCustomersResponse")
    @Action(input = "http://www.mac.com/CustomerDetails/allCustomersRequest", output = "http://www.mac.com/CustomerDetails/allCustomersResponse")
    public List<Customer> allCustomers();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.mac.client.Car>
     * @throws InvalidInputException_Exception
     */
    @WebMethod
    @WebResult(name = "Cars", targetNamespace = "")
    @RequestWrapper(localName = "customerCars", targetNamespace = "http://www.mac.com", className = "com.mac.client.CustomerCars")
    @ResponseWrapper(localName = "customerCarsResponse", targetNamespace = "http://www.mac.com", className = "com.mac.client.CustomerCarsResponse")
    @Action(input = "http://www.mac.com/CustomerDetails/customerCarsRequest", output = "http://www.mac.com/CustomerDetails/customerCarsResponse", fault = {
        @FaultAction(className = InvalidInputException_Exception.class, value = "http://www.mac.com/CustomerDetails/customerCars/Fault/InvalidInputException")
    })
    public List<Car> customerCars(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws InvalidInputException_Exception
    ;

}
