
package com.mac.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerDetailsImplService", targetNamespace = "http://service.mac.com/", wsdlLocation = "http://localhost:9999/ws/customer?wsdl")
public class CustomerDetailsImplService
    extends Service
{

    private final static URL CUSTOMERDETAILSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERDETAILSIMPLSERVICE_EXCEPTION;
    private final static QName CUSTOMERDETAILSIMPLSERVICE_QNAME = new QName("http://service.mac.com/", "CustomerDetailsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/customer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERDETAILSIMPLSERVICE_WSDL_LOCATION = url;
        CUSTOMERDETAILSIMPLSERVICE_EXCEPTION = e;
    }

    public CustomerDetailsImplService() {
        super(__getWsdlLocation(), CUSTOMERDETAILSIMPLSERVICE_QNAME);
    }

    public CustomerDetailsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERDETAILSIMPLSERVICE_QNAME, features);
    }

    public CustomerDetailsImplService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERDETAILSIMPLSERVICE_QNAME);
    }

    public CustomerDetailsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERDETAILSIMPLSERVICE_QNAME, features);
    }

    public CustomerDetailsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerDetailsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerDetails
     */
    @WebEndpoint(name = "CustomerDetailsImplPort")
    public CustomerDetails getCustomerDetailsImplPort() {
        return super.getPort(new QName("http://service.mac.com/", "CustomerDetailsImplPort"), CustomerDetails.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerDetails
     */
    @WebEndpoint(name = "CustomerDetailsImplPort")
    public CustomerDetails getCustomerDetailsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.mac.com/", "CustomerDetailsImplPort"), CustomerDetails.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERDETAILSIMPLSERVICE_EXCEPTION!= null) {
            throw CUSTOMERDETAILSIMPLSERVICE_EXCEPTION;
        }
        return CUSTOMERDETAILSIMPLSERVICE_WSDL_LOCATION;
    }

}
